/*
 * Copyright (C) 2009-2018 by Benedict Paten (benedictpaten@gmail.com)
 *
 * Released under the MIT license, see LICENSE.txt
 */

#include "CuTest.h"
#include "margin.h"
#include "callConsensus.h"

static char *polishParamsFile = "../params/allParams.np.json";


void getCallConsensusDataFromReads(char *rawReads[], int readCount, char**rleReads[], uint8_t**rleCounts[], uint8_t *strands[]) {
    *rleReads = st_calloc(readCount, sizeof(char*));
    *rleCounts = st_calloc(readCount, sizeof(uint8_t*));
    *strands = st_calloc(readCount, sizeof(uint8_t));

    for (int i = 0; i < readCount; i++) {
        char *rawRead = rawReads[i];
        RleString *rleString = rleString_construct(rawRead);

        (*rleReads)[i] = stString_copy(rleString->rleString);
        (*rleCounts)[i] = st_calloc(rleString->length, sizeof(uint8_t));
        for (int j = 0; j < rleString->length; j++) {
            ((*rleCounts)[i])[j] = (uint8_t) rleString->repeatCounts[j];
        }
        (*strands)[i] = 0; //todo

        rleString_destruct(rleString);
    }
}


void test_readSet1(CuTest *testCase) {
	char *rawReads[] = {
            "CATTTTTCTCCTCCACCTGCAACAGAAGATAAAAACGCGCATCACAAACTACTTTATTG",
            "CATTTTTCTCTCCGTCACGTAATAGGAAAACAGATGAAAATGTGCACCATAAAACGCATTTTTATTT",
            "CATTTTCTCTCTCCGTCACGACAGGAAACAGATGAAAATGGGCACAAGACCACAAACGCATTTTGAT",
            "CATTTTTCTCCGGTCATTTAATGAAAACAGATGGTACTGCGTATGTGACATAAACGCATTTTTATTT",
            "CATTTCCTCCGTCACTGCACAGGAAAACAGATGAAAATGCAAGTATGGACCCACAAAACGCATTTTATTT",
            "CATTTTTTCTCTCTCCGTCAGCTGCATTGAAAATGATGAAATGCGGGTATGACTATAAACGCATTTATTT",
            "CATTTTTTTTCTCTCCTCCACACACAGGAAACAGATGAAAAATGTATGTGACCATAAAACGCATTTTATTT",
            "TATTTTCTCCGTCATTGCAGGAAAACAGATGAAATGTAAAGTATGTGAATTACAAACGGTTTTTTTTATTT",
            "CATTTTTCTCCTCCGTCATTGCACAGGAGTCAGATGAAAATGCGCATGTGACCATAACGCATTTTTTTATTT",
            "CATTTTTCTCCTCCGTCATACCGTGAAACAGATGAAAAATGCGGGCATGGGACCATAAAACGCATTTTTATTT",
            "CATTTTTCTCCTCCGTCATTGCACAGGAAAACAGATGAAAACGTGGGGCATGTGACCATAAACGCATTTTTATT",
            "CATTTTCTCTCCTCGTGTTGCACAGGAAAACAGATGAAAAATGCGAGATATGTGATCCACAAACATTTTTATTT",
            "CATTTTTCTCCTCCGTCATTGCACAGGAAAATGATGAAAATGCGGGGCATGTGACCATAAAACGCATTTTTATTT",
            "CATTTTCTCTCTCCCTCGTCATTGCACAGGAAAACAGATGAAAATGCAGGGCATGTGACCATAAAACGCATTTTTT",
            "CATTTTCTCTCCTCCACATTGCACAGGAAAACAGATGAAAATGCGGCATGTGACCATAAAACGCATTTCTTTATTT",
            "CATTTTCTCCGTCAGTCAACAATATGAAAACAGATGAAACGCGGGCACGTGACCATAAAACGCATTTTTTTTATTT",
            "CATTTTTCTCCTCCGTCATTGCATTGTGGAACAGATGAAAATGCGGGGTATGTGAATCATAAAACGCATTTTATTT",
            "CATTTTTCTCTCCGTCATTGCATTAGAAAACAGGGATGAAAATGCGGGCATGTGACCATAAAAACGCATTTTTATTT",
            "CATTTTTCTCTCTCCTCCGTCATTGCACAGGAAAACAGATGAAAAATGCGCGTGACTATAAAACGCATTTTTATTTT",
            "CATTTTCCTCTCCCTCCGTCATTTGCACAGGAAAACAGATGAAAAAATGCGGAATGGCTATTATAAACATTTTTAACT",
            "CATTTTTTTCTCCTCTGTCATTGCACAGGAAAACAGATGAAAAATGCGTATGTGACCATAAAATCCATTTCTTTTATTT",
            "CATTTTTCTCCTCCGTCATTGCACAGGAAAATGATGAAAAAATGCGGGCATGTGACCATAAAACGTGCATTTTTTATTT",
            "CATTTTCTCTCTCCTCCGTGTTGCACAGGAAAACCAGATGAAAATGCGGAACATGTGTTCATAAAACGCATTTTTATTT",
            "CATTTTCTCTCCCTCCGTCATTGCACAGGAAAACAGATGAAAATGCAGGGCAATAATGACCATAAAACGCATTTTTATTT",
            "CATTTTCTCTCCTCTCGTCATTTGCACAGGAAGAGCAGATGAAAATGCAGGGCATGTGACCATAAAACGCATTTTTATTT",
            "CCATTTTCTCTCTCCCTCCGTCATTGCACAGGAAAAGCAGATGAAAAATGCGGGCATGTGACCATAAAACGCATTTTATTT",
            "CATTTTTTTCTCTCCTGTCATTGCACAGGAAACAAAGAGATGAAAAATGCGGGCATGTGACCATAAAACGCATTTTTATTT",
            "CATTTTTCTCTCCCTCCGTCATTGCATAGGAAAACAGATGAAAATGCGGGGTATGTGGACCATAAAACGCATTTTTTATTT",
            "CATTTTCTCTCTCCCTCCGTCATTGCACAGGGAAAACAGATGAAAATTGCGGGGCATGTGACCATAAAACGCATTTTTATTT",
            "CATTTTCTCTCTCCCTCCGTCATTTGCACAGGAAAACAGATGAAAAATGCGGGGCATGTGACCATAAAACGCATTTTTTATTT",
            "CATTTTTCTCTCCCTCCGTCACTGCACAGGAAAAACAGATGAAAATGCGGGGCATGCATCATAAAACGTATTTTTATTGAATTT",
            "CATTTTCTCTCTCCCTCCGTCATTGCACAGGAAAACAGATAAGAAAAATGCAGGGGCATGTGACCATAAAACGCATTTTTATTT",
            "CATTTTTTCACTACTCTCCCTCCGTCGTACTGGAAAACAAACAGATAAATGCAGGGCATGTGACCATAAAACATTTTTTTATTT",
            "CATTTTTCTCTCTCCCTCCGTCATTGCACAGGAAAACAGATAAAAAAAAATGCAGGGGCATGTGACCATAAAACATTTTTATTT",
            "CATTTTTTCTCTCTCTCGTGTTGCACACAGGAAAACAGATGAAAAATGCCGGGGCATCATGACCATAAAACGCGTTTTTTTATTT",
            "CATTTTCTCTCTCCCTCCGTCATTGCACAGGAAAACAGATGAAAAATGCAGGGGCGTAACTGACCATAAAACGCATTTTTTATTT",
            "CATTTTTTCTCTCCTCCGTCATTGCACAGGAAAAATGTGATGAAAATGCGGGGTATGTGACCATAAAACGCATTTTTATGCTTCT",
            "CATTTTCTCTCTCCCTCCGTCATTGCACAGGAAAACAGATGAAAAATGCGAGGACATGTGACCATAAAACGCATTTTTTTTATTT",
            "CATTTTCTCTCTCCCTCCGTCCATTGCACAGGAAAACAGATATAAAAAATGCAGGGCATCAAACCATAAAACATTTTTTTTATTT",
            "CATTTTTCTCTCCCTCCGTCATTGCAATAGGAAAACAGATATTTTGGTGTACCGCAAGTATGTGACCATAAAACGTATTTTTATTT",
            "CATTTTCTCTCTCCCTCCGTCATTGCACAGGAAAACCAGATAGAAAAAATACAGGGCATGTGTTCATAAAGCACGCATTTTTATTT",
            "CATTTTTTTCTCTCTCCTCCGCTTTCACACACAGGAGTAAACAGATGAAAAATGTGGGCATGTGACCATAAAACGCATTTTTTATTT",
            "CATTTTCTCTCTCCCTCAAAATCATTTGCACAGGAAAACAGATAGAAAAATGCAACGGGGCATGTGATATAAAACGCATTTTTTATTT",
            "CATTTTCTACTCTCTCCCTCCGTCATTGCAGGAAAACAGATGAAAATGCAGGGAACATATATGACCATAAAACGCATTTTTTTTTATTT",
            "CATTTTCTCTCTCCCTCCGTCATTGCACAGGAAAACAGATGAAAAAAGAGCTGGCATGCGGGGCATGTGACCATAAAACGCATTTTTTTGT"
    };
    int readCount = 45;

    char **rleReads = NULL;
    uint8_t **rleCounts = NULL;
    uint8_t *strands = NULL;
    getCallConsensusDataFromReads(rawReads, readCount, &rleReads, &rleCounts, &strands);
    PolishParams *params = getConsensusParameters(polishParamsFile);

    // get consensus string
    char *consensus = callConsensus(readCount, rleReads, rleCounts, strands, params);

    CuAssertTrue(testCase, strlen(consensus) > 0);

    // cleanup
    for (int64_t i = 0; i < readCount; i++) {
        free(rleReads[i]);
        free(rleCounts[i]);
    }
    free(rleReads);
    free(rleCounts);
    free(strands);
}


void test_readSet2(CuTest *testCase) {
	char *rawReads[] = {
            "GATGTAAAAATGACTGAGTTAGAACAGGCATAAATACATCTGT",
            "GATGTAAAAAAAAATGACAGAGAATAAAACTATCCTTATCTATT",
            "GATGTAAAAAGAAGCGGAAGTTAGAACAGGCATAAATACATCTGT",
            "GATGTAAAAAGAAATGACGGAAGAACAGAGCATAACACACATCTGT",
            "GATGTAAAAAAAGAATGATTTAGTTGAACAGAGCATAAATATCTGT",
            "GATGTAAAAAAAAGAAATGACGGAAGAACAGAGCATAACACATCTGT",
            "GATGTAAAAGAAATGGAGGTTAGAACAGAGCATAAATACACATCTGT",
            "GATGTAAAAAAAGAAATGATTTGGAAGAACAGAGCATAAATATCTGT",
            "GATGTAAAAGAAATGACGGAAGTTAGAATATATATAACACACATCTGT",
            "GATGTAAAAAAAGAATGGACGGTTAGAACAGAGCACAACACACATCTGT",
            "GATGTAAAAAAGAATGATAAAGTTAGAATAGAGCATAAATAACATCTGT",
            "GATGTAAAAGAAATGTGGAAGTTAGAACAGAGCATAAATACACATCTAT",
            "GATGTAAAAAAAAAGAAATGAAGCTAGAACAGAGCATAAATACATCTGT",
            "GATGTAAAAAAAAAATGACCCGGAAGTTGAACAGAGCATAATACATCTGT",
            "GATGTAAAAAAGAAATGATTTAAAGGAACAGAGCATAAATACACATCTGT",
            "GATGTAAAAAAAAGTGACGGAAGTTAAGACAGGCATAAATACACATCTGT",
            "GATGTAAAAAAGAAATGATTTGCTAGAACAGAGCATAAATACACATCTGT",
            "GATGTAAAAAAAGAAATGATGGGTTAGAATAGAGCATAAATACACATCTGT",
            "GATGTAAAAAAAAGAAATGACGAGTTAGAACCAGAGCACCATCTACATCAT",
            "GATGTAAAAAAAAAAATGACGGAAGTTAGACAAGCATAAATACACATCTAT",
            "GATGTAAAAAAAAGAATGATTTGAAGTTAGAACAGAGCATAACACATCTGT",
            "GATGTAAAAGAAAATCGACTGAAGTTAGAACAGAGCATAAATACACATCTGT",
            "GATGTAAAAAAAGAATGACGGAAGTTAGAACAGAGCATAAATACACATCTGT",
            "GATGTAAAAAAAGAAATGACGGAGTTAGAACAGAGCATAAATACACATCTAT",
            "GATGTAAAAAAAAAGAAATGTGTGAGTTAAGACAGAGCATAAATACATCTAT",
            "GATGTAAAAAAGAAATGACGGAAGTTAAGACAGAGCATAAATACACATCTATT",
            "GATGTAAAAAAAAAAATGTGGAAGTTAAAACAGAGCATAAATACACATCTATT",
            "GATGCAAAAAAAAAGAAATGACGGAAGTTAAATTAGAGCATAAATACATCTGT",
            "GATGTAAAAAAAAGAAATGATTTGGAAGTTACAGAGCATAAATACACATCTGT",
            "GATGTAAAGAAAATGATTTTAGAAGTTAGAACAGAGCATAACACAATATCTGT",
            "GATAAAAAAAAAGGAATGATTGGAAGCTAGAACAGAGCATAAATACACATCTGT",
            "GATGTAAAAAAAAGAAATGACGGAAGTTAAGACAGAGCATAAATACACATCTGT",
            "GATGTAAAAAAAAATGACGGAAGTTCTGAAACAGGCATAAATACACATCTGTAT",
            "GATGTAAAAAGAATGATTTGAAGTTAGAACAGAGTATATTAAATACACATCTGT",
            "GATGTAAAAAAAAAGAAATGACGGAAGTTAAGACAGAGCATAAATACACATCTATT",
            "GATGTAAAAAAAAAGAAATGATTTGAAGCAGAACAGAGCATAAATACAAGATCTGT",
            "GATGTAAAAAAAAGAAGAAATGACGGAAGTTAAACAGAGCATAAATACACATCTGT",
            "GATGTAAAAAAAAAAGAAATGATTGAAGTTAGAAATATACATAAATACACATCTGT",
            "GATGTAAAAAAAAAGAAATGATTTTAAAGTGAACAGAGCATAAATACACACCTTGGT",
            "GATGTAAAAAAAAAAAAGAAATGACGGAAGTTGAACTAGGCTTATAAATACATCTGT",
            "GATGCCAAAAAAAAAAAGAAATGGCCAGAGTTAGAACAGAGCATAAATACACATCTGT",
            "GATGTAAAAAAAAAGAAATGCGGATTTGGAAGTTAGAACAGTATATAAAGCACACATCCGT"
    };
    int readCount = 42;

    char **rleReads = NULL;
    uint8_t **rleCounts = NULL;
    uint8_t *strands = NULL;
    getCallConsensusDataFromReads(rawReads, readCount, &rleReads, &rleCounts, &strands);
    PolishParams *params = getConsensusParameters(polishParamsFile);

    // get consensus string
    char *consensus = callConsensus(readCount, rleReads, rleCounts, strands, params);

    CuAssertTrue(testCase, strlen(consensus) > 0);

    for (int64_t i = 0; i < readCount; i++) {
        free(rleReads[i]);
        free(rleCounts[i]);
    }
    free(rleReads);
    free(rleCounts);
    free(strands);
}


CuSuite* callConsensusTestSuite(void) {
    CuSuite* suite = CuSuiteNew();

    SUITE_ADD_TEST(suite, test_readSet1);
    SUITE_ADD_TEST(suite, test_readSet2);

    return suite;
}
